PROJECT = svmlab

BIN_DIR = bin

GO_DIR = ipx
GO_SERVER_BIN = server

# swag is a code generator installed separately from the module's
# dependencies, so a fresh checkout will not have it. Fall back to GOPATH/bin,
# which is where go install puts it but is often missing from PATH.
#
# The CLI version must match the swaggo/swag version pinned in go.mod: docs
# generated by a newer CLI fail to compile against an older library.
SWAG_VERSION = v1.16.6
SWAG ?= $(shell command -v swag 2>/dev/null || echo $(shell go env GOPATH)/bin/swag)

.PHONY: help \
	go-build go-build-server server \
	swag swag-install go-test fmt vet tidy \
	clean

help:
	@echo "$(PROJECT) commands:"
	@echo ""
	@echo "  make go-build          Build all Go binaries"
	@echo "  make go-build-server   Build server binary"
	@echo "  make server            Regenerate docs, build, and run the API server"
	@echo ""
	@echo "  make swag              Regenerate Swagger docs"
	@echo "  make swag-install      Install the swag CLI at the pinned version"
	@echo "  make go-test           Run Go tests"
	@echo "  make fmt               Format Go sources"
	@echo "  make vet               Run go vet"
	@echo "  make tidy              Tidy go.mod and go.sum"
	@echo ""
	@echo "  make clean             Remove generated build outputs"

$(BIN_DIR):
	mkdir -p $(BIN_DIR)

go-build-server: $(BIN_DIR)
	cd $(GO_DIR) && go build -o ../$(BIN_DIR)/$(GO_SERVER_BIN) ./cmd/server

go-build: go-build-server

# swag runs first: the generated docs package is compiled into the binary, so
# building before regenerating would serve the previous run's spec.
server: swag go-build-server
	./$(BIN_DIR)/$(GO_SERVER_BIN)

swag:
	@[ -x "$(SWAG)" ] || { \
		echo "error: swag not found."; \
		echo "  install: go install github.com/swaggo/swag/cmd/swag@$(SWAG_VERSION)"; \
		echo "  then add it to PATH: export PATH=\"\$$PATH:$$(go env GOPATH)/bin\""; \
		exit 1; \
	}
	cd $(GO_DIR) && $(SWAG) init -g cmd/server/main.go -o docs

swag-install:
	go install github.com/swaggo/swag/cmd/swag@$(SWAG_VERSION)

go-test:
	cd $(GO_DIR) && go test ./...

fmt:
	cd $(GO_DIR) && gofmt -w .

vet:
	cd $(GO_DIR) && go vet ./...

tidy:
	cd $(GO_DIR) && go mod tidy

clean:
	rm -rf $(BIN_DIR)
