// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/svm/rpc/": {
            "post": {
                "description": "Passes a method straight through, so anything this API has not wrapped stays reachable.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rpc"
                ],
                "summary": "Call any JSON-RPC method",
                "parameters": [
                    {
                        "description": "Method and params",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/misc.RawRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Chain name, e.g. solana",
                        "name": "X-Chain-Name",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Chain network, e.g. testnet",
                        "name": "X-Chain-Network",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/svm/rpc/account": {
            "post": {
                "description": "Returns the owner, executable flag, data size, and data. An account that does not exist is reported with exists=false rather than as an error, since most 32-byte values name one nobody has created.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rpc"
                ],
                "summary": "Read an account's on-chain state",
                "parameters": [
                    {
                        "description": "Account",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/misc.AccountRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Chain name, e.g. solana",
                        "name": "X-Chain-Name",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Chain network, e.g. testnet",
                        "name": "X-Chain-Network",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/misc.AccountResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/svm/rpc/airdrop": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rpc"
                ],
                "summary": "Fund an account on devnet or testnet",
                "parameters": [
                    {
                        "description": "Account and amount",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/misc.AirdropRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Chain name, e.g. solana",
                        "name": "X-Chain-Name",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Chain network, e.g. testnet",
                        "name": "X-Chain-Network",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/misc.AirdropResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/svm/rpc/balance": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rpc"
                ],
                "summary": "Read an account's balance",
                "parameters": [
                    {
                        "description": "Account",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/misc.AccountRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Chain name, e.g. solana",
                        "name": "X-Chain-Name",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Chain network, e.g. testnet",
                        "name": "X-Chain-Network",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/misc.BalanceResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/svm/rpc/batch": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rpc"
                ],
                "summary": "Call several JSON-RPC methods in one round trip",
                "parameters": [
                    {
                        "description": "Calls",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/misc.BatchRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Chain name, e.g. solana",
                        "name": "X-Chain-Name",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Chain network, e.g. testnet",
                        "name": "X-Chain-Network",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/svm/rpc/blockhash": {
            "post": {
                "description": "Returns the blockhash to build against and the block height past which it is rejected, so expiry can be checked rather than guessed. Fetched at finalized commitment, since a blockhash from a less settled view risks belonging to a fork.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rpc"
                ],
                "summary": "Read a recent blockhash",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Chain name, e.g. solana",
                        "name": "X-Chain-Name",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Chain network, e.g. testnet",
                        "name": "X-Chain-Network",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/misc.BlockhashResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/svm/rpc/fee": {
            "post": {
                "description": "The fee follows from the signature count and any compute budget instructions, both of which live in the message, so it is known before signing and cannot be exceeded by execution the way a gas estimate can.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rpc"
                ],
                "summary": "Price a message",
                "parameters": [
                    {
                        "description": "Message",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/misc.FeeRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Chain name, e.g. solana",
                        "name": "X-Chain-Name",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Chain network, e.g. testnet",
                        "name": "X-Chain-Network",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/misc.FeeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/svm/rpc/genesis-hash": {
            "post": {
                "description": "A genesis hash is not folded into a signature the way EIP-155 binds a chain id, so nothing on chain prevents a transaction from replaying on another cluster. Comparing what the endpoint reports against what config names is the substitute check.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rpc"
                ],
                "summary": "Read the cluster's genesis hash and compare it to config",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Chain name, e.g. solana",
                        "name": "X-Chain-Name",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Chain network, e.g. testnet",
                        "name": "X-Chain-Network",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/misc.GenesisHashResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/svm/rpc/health": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rpc"
                ],
                "summary": "Read the node's health",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Chain name, e.g. solana",
                        "name": "X-Chain-Name",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Chain network, e.g. testnet",
                        "name": "X-Chain-Network",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/misc.HealthResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/svm/rpc/rent-exemption/mint": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rpc"
                ],
                "summary": "Minimum balance for an SPL Token mint",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Chain name, e.g. solana",
                        "name": "X-Chain-Name",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Chain network, e.g. testnet",
                        "name": "X-Chain-Network",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/misc.RentExemptionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/svm/rpc/rent-exemption/public-key": {
            "post": {
                "description": "Reads the size from a live account, which covers layouts none of the named endpoints describe. Pass a raw byte count to the getMinimumBalanceForRentExemption method through the raw endpoint instead.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rpc"
                ],
                "summary": "Minimum balance for an account of the same size as an existing one",
                "parameters": [
                    {
                        "description": "Account",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/misc.AccountRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Chain name, e.g. solana",
                        "name": "X-Chain-Name",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Chain network, e.g. testnet",
                        "name": "X-Chain-Network",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/misc.RentExemptionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/svm/rpc/rent-exemption/stake": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rpc"
                ],
                "summary": "Minimum balance for a stake account",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Chain name, e.g. solana",
                        "name": "X-Chain-Name",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Chain network, e.g. testnet",
                        "name": "X-Chain-Network",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/misc.RentExemptionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/svm/rpc/rent-exemption/system": {
            "post": {
                "description": "A wallet holds lamports and no data, so this is the floor any account must clear. It is also what a transfer to a previously unused address has to meet, since the transfer creates the account.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rpc"
                ],
                "summary": "Minimum balance for a plain wallet",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Chain name, e.g. solana",
                        "name": "X-Chain-Name",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Chain network, e.g. testnet",
                        "name": "X-Chain-Network",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/misc.RentExemptionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/svm/rpc/rent-exemption/token": {
            "post": {
                "description": "Every token balance lives in an account of its own, so opening a position in a new token costs this much before any tokens move.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rpc"
                ],
                "summary": "Minimum balance for an SPL Token account",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Chain name, e.g. solana",
                        "name": "X-Chain-Name",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Chain network, e.g. testnet",
                        "name": "X-Chain-Network",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/misc.RentExemptionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/svm/rpc/rent-exemption/vote": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rpc"
                ],
                "summary": "Minimum balance for a validator vote account",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Chain name, e.g. solana",
                        "name": "X-Chain-Name",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Chain network, e.g. testnet",
                        "name": "X-Chain-Network",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/misc.RentExemptionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/svm/rpc/slot": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rpc"
                ],
                "summary": "Read the current slot",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Chain name, e.g. solana",
                        "name": "X-Chain-Name",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Chain network, e.g. testnet",
                        "name": "X-Chain-Network",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/misc.SlotResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/svm/rpc/transaction/send": {
            "post": {
                "description": "Submits a fully signed transaction to the cluster and returns its signature. Acceptance is not execution; the transaction still has to land in a block.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rpc"
                ],
                "summary": "Broadcast a signed transaction",
                "parameters": [
                    {
                        "description": "Signed transaction",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/misc.SendTransactionRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Chain name, e.g. solana",
                        "name": "X-Chain-Name",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Chain network, e.g. testnet",
                        "name": "X-Chain-Network",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/misc.SendTransactionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/svm/rpc/transaction/simulate": {
            "post": {
                "description": "Runs a fully signed transaction against the node's state without broadcasting it, and returns the program logs either way. The logs are the only account of why execution stopped; nothing here corresponds to a revert string.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rpc"
                ],
                "summary": "Execute a transaction without submitting it",
                "parameters": [
                    {
                        "description": "Transaction",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/misc.SimulateTransactionRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Chain name, e.g. solana",
                        "name": "X-Chain-Name",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Chain network, e.g. testnet",
                        "name": "X-Chain-Network",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/misc.SimulateTransactionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/svm/rpc/transaction/status": {
            "post": {
                "description": "Stands in for an EVM receipt, but found can stay false forever: a transaction whose blockhash expired is forgotten and never lands.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rpc"
                ],
                "summary": "Read a transaction's status",
                "parameters": [
                    {
                        "description": "Signature",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/misc.SignatureStatusRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Chain name, e.g. solana",
                        "name": "X-Chain-Name",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Chain network, e.g. testnet",
                        "name": "X-Chain-Network",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/misc.SignatureStatusResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/svm/rpc/version": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rpc"
                ],
                "summary": "Read the node's software version",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Chain name, e.g. solana",
                        "name": "X-Chain-Name",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Chain network, e.g. testnet",
                        "name": "X-Chain-Network",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/misc.VersionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/svm/sign": {
            "post": {
                "description": "Signs the given bytes with a key resolved from config.yaml and returns the bare signature, assembling nothing around it. The input is the message itself, not a digest: ed25519 hashes internally, so a pre-hashed input yields a signature no verifier holding the real message can check. Pass the message field a build returns to reproduce what the transaction signer does.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sign"
                ],
                "summary": "Sign arbitrary bytes",
                "parameters": [
                    {
                        "description": "Signer public key and message",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/misc.SignRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Chain name, e.g. solana",
                        "name": "X-Chain-Name",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Chain network, e.g. testnet",
                        "name": "X-Chain-Network",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/misc.SignResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/svm/sign/transaction": {
            "post": {
                "description": "Signs the message inside a serialized transaction and writes each signature into its signer's slot. The message is never rebuilt, so the bytes a caller signs are exactly the bytes they were given. Signers are named by public key and resolved from config.yaml. Keys may be named across several calls, so co-signers can complete a transaction one at a time.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sign"
                ],
                "summary": "Sign a serialized transaction",
                "parameters": [
                    {
                        "description": "Transaction and signer public keys",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/misc.SignTransactionRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Chain name, e.g. solana",
                        "name": "X-Chain-Name",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Chain network, e.g. testnet",
                        "name": "X-Chain-Network",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/misc.SignTransactionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/svm/sign/verify": {
            "post": {
                "description": "Checks a signature against a message and a public key. The key is required and cannot be recovered from the signature, since ed25519 offers no equivalent of ecrecover. Any key may be given, not only one from config.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sign"
                ],
                "summary": "Verify a signature",
                "parameters": [
                    {
                        "description": "Public key, message, and signature",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/misc.VerifyRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Chain name, e.g. solana",
                        "name": "X-Chain-Name",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Chain network, e.g. testnet",
                        "name": "X-Chain-Network",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/misc.VerifyResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/svm/v1/transaction/build": {
            "post": {
                "description": "Compiles instructions into a message and returns the unsigned transaction, the message bytes every signer signs, and the account ordering the compilation produced",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transaction"
                ],
                "summary": "Build an unsigned transaction",
                "parameters": [
                    {
                        "description": "Fee payer, blockhash, and instructions",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.BuildTransactionRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Chain name, e.g. solana",
                        "name": "X-Chain-Name",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Chain network, e.g. testnet",
                        "name": "X-Chain-Network",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.BuildTransactionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/svm/v2/transaction/system/transfer": {
            "post": {
                "description": "Assembles a System Program transfer and returns the same shape as a v1 build, so sign and send accept it unchanged. The recent blockhash is always fetched, and the recipient is not required to exist yet. To send the sender's entire balance, use transfer/max instead.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transaction"
                ],
                "summary": "Build a native SOL transfer",
                "parameters": [
                    {
                        "description": "Sender, recipient, and amount",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v2.SystemTransferRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Chain name, e.g. solana",
                        "name": "X-Chain-Name",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Chain network, e.g. testnet",
                        "name": "X-Chain-Network",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v2.SystemTransferResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/svm/v2/transaction/system/transfer/max": {
            "post": {
                "description": "Assembles a System Program transfer moving everything the sender can send. Resolving that amount needs the sender's balance and the fee, both fetched from the chain. The fee only comes out of the sender's balance when the sender is also the fee payer; with a separate fee payer the whole balance can go, which empties the account and lets the runtime reclaim it.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transaction"
                ],
                "summary": "Build a native SOL transfer of the sender's entire balance",
                "parameters": [
                    {
                        "description": "Sender and recipient",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v2.SystemTransferMaxRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Chain name, e.g. solana",
                        "name": "X-Chain-Name",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Chain network, e.g. testnet",
                        "name": "X-Chain-Network",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v2.SystemTransferMaxResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "misc.AccountRequest": {
            "type": "object",
            "properties": {
                "public_key": {
                    "type": "string",
                    "example": "EodYvwsT22JTdNmvCeC974WjPiVYcxvfGpYLJxnB3JqK"
                }
            }
        },
        "misc.AccountResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "string"
                },
                "executable": {
                    "type": "boolean"
                },
                "exists": {
                    "type": "boolean"
                },
                "lamports": {
                    "type": "string"
                },
                "owner": {
                    "type": "string"
                },
                "public_key": {
                    "type": "string"
                },
                "sol": {
                    "type": "string"
                },
                "space": {
                    "type": "integer"
                }
            }
        },
        "misc.AirdropRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string",
                    "example": "1000000000"
                },
                "public_key": {
                    "type": "string"
                }
            }
        },
        "misc.AirdropResponse": {
            "type": "object",
            "properties": {
                "signature": {
                    "type": "string"
                }
            }
        },
        "misc.BalanceResponse": {
            "type": "object",
            "properties": {
                "lamports": {
                    "type": "string"
                },
                "public_key": {
                    "type": "string"
                },
                "sol": {
                    "type": "string"
                }
            }
        },
        "misc.BatchCall": {
            "type": "object",
            "properties": {
                "method": {
                    "type": "string"
                },
                "params": {}
            }
        },
        "misc.BatchRequest": {
            "type": "object",
            "properties": {
                "calls": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/misc.BatchCall"
                    }
                }
            }
        },
        "misc.BlockhashResponse": {
            "type": "object",
            "properties": {
                "blockhash": {
                    "type": "string"
                },
                "last_valid_block_height": {
                    "type": "integer"
                }
            }
        },
        "misc.FeeRequest": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "misc.FeeResponse": {
            "type": "object",
            "properties": {
                "lamports": {
                    "type": "string"
                },
                "sol": {
                    "type": "string"
                },
                "valid": {
                    "type": "boolean"
                }
            }
        },
        "misc.GenesisHashResponse": {
            "type": "object",
            "properties": {
                "configured": {
                    "type": "string"
                },
                "genesis_hash": {
                    "type": "string"
                },
                "matches": {
                    "type": "boolean"
                }
            }
        },
        "misc.HealthResponse": {
            "type": "object",
            "properties": {
                "health": {
                    "type": "string"
                }
            }
        },
        "misc.RawRequest": {
            "type": "object",
            "properties": {
                "method": {
                    "type": "string",
                    "example": "getEpochInfo"
                },
                "params": {}
            }
        },
        "misc.RentExemptionResponse": {
            "type": "object",
            "properties": {
                "account_type": {
                    "type": "string"
                },
                "lamports": {
                    "type": "string"
                },
                "sol": {
                    "type": "string"
                },
                "space": {
                    "type": "integer"
                }
            }
        },
        "misc.SendTransactionRequest": {
            "type": "object",
            "properties": {
                "transaction": {
                    "type": "string"
                }
            }
        },
        "misc.SendTransactionResponse": {
            "type": "object",
            "properties": {
                "signature": {
                    "type": "string"
                }
            }
        },
        "misc.SignRequest": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "public_key": {
                    "type": "string",
                    "example": "EodYvwsT22JTdNmvCeC974WjPiVYcxvfGpYLJxnB3JqK"
                }
            }
        },
        "misc.SignResponse": {
            "type": "object",
            "properties": {
                "public_key": {
                    "type": "string"
                },
                "signature": {
                    "type": "string"
                }
            }
        },
        "misc.SignTransactionRequest": {
            "type": "object",
            "properties": {
                "public_keys": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "EodYvwsT22JTdNmvCeC974WjPiVYcxvfGpYLJxnB3JqK"
                    ]
                },
                "transaction": {
                    "type": "string"
                }
            }
        },
        "misc.SignTransactionResponse": {
            "type": "object",
            "properties": {
                "fully_signed": {
                    "type": "boolean"
                },
                "signatures": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "transaction": {
                    "type": "string"
                },
                "transaction_id": {
                    "type": "string"
                }
            }
        },
        "misc.SignatureStatusRequest": {
            "type": "object",
            "properties": {
                "signature": {
                    "type": "string"
                }
            }
        },
        "misc.SignatureStatusResponse": {
            "type": "object",
            "properties": {
                "confirmation_status": {
                    "type": "string"
                },
                "confirmations": {
                    "type": "integer"
                },
                "err": {
                    "type": "string"
                },
                "failed": {
                    "type": "boolean"
                },
                "found": {
                    "type": "boolean"
                },
                "signature": {
                    "type": "string"
                },
                "slot": {
                    "type": "integer"
                }
            }
        },
        "misc.SimulateTransactionRequest": {
            "type": "object",
            "properties": {
                "transaction": {
                    "type": "string"
                }
            }
        },
        "misc.SimulateTransactionResponse": {
            "type": "object",
            "properties": {
                "err": {
                    "type": "string"
                },
                "failed": {
                    "type": "boolean"
                },
                "logs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "units_consumed": {
                    "type": "integer"
                }
            }
        },
        "misc.SlotResponse": {
            "type": "object",
            "properties": {
                "slot": {
                    "type": "integer"
                }
            }
        },
        "misc.VerifyRequest": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "public_key": {
                    "type": "string",
                    "example": "EodYvwsT22JTdNmvCeC974WjPiVYcxvfGpYLJxnB3JqK"
                },
                "signature": {
                    "type": "string"
                }
            }
        },
        "misc.VerifyResponse": {
            "type": "object",
            "properties": {
                "valid": {
                    "type": "boolean"
                }
            }
        },
        "misc.VersionResponse": {
            "type": "object",
            "properties": {
                "version": {
                    "type": "object",
                    "additionalProperties": {}
                }
            }
        },
        "v1.Account": {
            "type": "object",
            "properties": {
                "is_signer": {
                    "type": "boolean",
                    "example": true
                },
                "is_writable": {
                    "type": "boolean",
                    "example": true
                },
                "public_key": {
                    "type": "string",
                    "example": "EodYvwsT22JTdNmvCeC974WjPiVYcxvfGpYLJxnB3JqK"
                }
            }
        },
        "v1.BuildTransactionRequest": {
            "type": "object",
            "properties": {
                "fee_payer": {
                    "type": "string",
                    "example": "EodYvwsT22JTdNmvCeC974WjPiVYcxvfGpYLJxnB3JqK"
                },
                "instructions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.Instruction"
                    }
                },
                "recent_blockhash": {
                    "description": "RecentBlockhash may be left empty, in which case it is fetched from the\ncluster. Supplying it makes the call deterministic, which is what allows\nthe same request to reproduce identical bytes.",
                    "type": "string",
                    "example": ""
                }
            }
        },
        "v1.BuildTransactionResponse": {
            "type": "object",
            "properties": {
                "account_keys": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "header": {
                    "$ref": "#/definitions/v1.Header"
                },
                "message": {
                    "type": "string"
                },
                "recent_blockhash": {
                    "type": "string"
                },
                "signers": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "size": {
                    "type": "integer"
                },
                "transaction": {
                    "type": "string"
                }
            }
        },
        "v1.Header": {
            "type": "object",
            "properties": {
                "num_readonly_signed_accounts": {
                    "type": "integer"
                },
                "num_readonly_unsigned_accounts": {
                    "type": "integer"
                },
                "num_required_signatures": {
                    "type": "integer"
                }
            }
        },
        "v1.Instruction": {
            "type": "object",
            "properties": {
                "accounts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.Account"
                    }
                },
                "data": {
                    "type": "string",
                    "example": "AgAAAECcAAAAAAAA"
                },
                "program_id": {
                    "type": "string",
                    "example": "11111111111111111111111111111111"
                }
            }
        },
        "v2.SystemTransferMaxRequest": {
            "type": "object",
            "properties": {
                "fee_payer": {
                    "type": "string",
                    "example": "EodYvwsT22JTdNmvCeC974WjPiVYcxvfGpYLJxnB3JqK"
                },
                "from": {
                    "type": "string",
                    "example": "EodYvwsT22JTdNmvCeC974WjPiVYcxvfGpYLJxnB3JqK"
                },
                "to": {
                    "type": "string",
                    "example": "Cc81es6UdN5EwjE27Pv4ZFaQhd6yh4XG5n11SNd8pmxo"
                }
            }
        },
        "v2.SystemTransferMaxResponse": {
            "type": "object",
            "properties": {
                "account_keys": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "amount": {
                    "type": "string"
                },
                "amount_sol": {
                    "type": "string"
                },
                "fee": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "recent_blockhash": {
                    "type": "string"
                },
                "signers": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "transaction": {
                    "type": "string"
                }
            }
        },
        "v2.SystemTransferRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string",
                    "example": "1000000"
                },
                "fee_payer": {
                    "type": "string",
                    "example": "EodYvwsT22JTdNmvCeC974WjPiVYcxvfGpYLJxnB3JqK"
                },
                "from": {
                    "type": "string",
                    "example": "EodYvwsT22JTdNmvCeC974WjPiVYcxvfGpYLJxnB3JqK"
                },
                "to": {
                    "type": "string",
                    "example": "Cc81es6UdN5EwjE27Pv4ZFaQhd6yh4XG5n11SNd8pmxo"
                }
            }
        },
        "v2.SystemTransferResponse": {
            "type": "object",
            "properties": {
                "account_keys": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "amount": {
                    "description": "Amount and Fee are strings for the same reason the request's amount is:\na JSON number is a float, so a lamport count past 2^53 would reach a\nJavaScript client already rounded.",
                    "type": "string"
                },
                "amount_sol": {
                    "type": "string"
                },
                "fee": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "recent_blockhash": {
                    "type": "string"
                },
                "signers": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "transaction": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:33153",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "SVMlab API",
	Description:      "Solana transaction API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
